# Generated by Django 6.0.3 on 2026-03-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invalidatedtoken',
            new_name='invalidated_expiryT_85f134_idx',
            old_name='invalidated__expiryT_eb047f_idx',
        ),
    ]
