# Generated by Django 6.0.3 on 2026-03-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0002_rename_password_hash_user_password'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_active_category_name',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_active_category_name'),
        ),
    ]
