# Generated by Django 6.0.3 on 2026-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_remove_category_unique_active_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
