# Generated by Django 6.0.3 on 2026-05-24 22:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_color_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'default_categories',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'type'), name='unique_default_category_name_type')],
            },
        ),
    ]
