# Generated by Django 6.0.3 on 2026-05-11 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0002_rename_password_hash_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatmessage',
            name='session',
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='user',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.DeleteModel(
            name='AIChatSession',
        ),
    ]
