# Generated by Django 6.0.3 on 2026-05-11 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_aichatmessage_session_aichatmessage_user_and_more'),
        ('users', '0002_rename_password_hash_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatmessage',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
