"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return

    for line in dotenv_path.read_text(encoding="utf-8").splitlines():
        item = line.strip()
        if not item or item.startswith("#") or "=" not in item:
            continue
        key, value = item.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


_load_dotenv(BASE_DIR / ".env")


def _get_env(name: str, required: bool = True) -> str:
    value = os.getenv(name)
    if required and (value is None or value == ""):
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value or ""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _get_env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_env("DEBUG", required=False).lower() == "true"

ALLOWED_HOSTS = [h.strip() for h in _get_env("ALLOWED_HOSTS").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "apps.users",
    "core.authentication",
    "apps.categories",
    "apps.transactions",
    "apps.budgets",
    "apps.chats",
    "apps.admin_dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.common.CommonMiddleware",
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": _get_env("DB_ENGINE"),
        "NAME": _get_env("DB_NAME"),
        "USER": _get_env("DB_USER"),
        "PASSWORD": _get_env("DB_PASSWORD"),
        "HOST": _get_env("DB_HOST"),
        "PORT": _get_env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

PASSWORD_HASHERS = [
    "config.hashers.BCrypt10PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Ho_Chi_Minh"
USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


JWT_SECRET_KEY = _get_env("JWT_SECRET_KEY")
JWT_ALGORITHM = _get_env("JWT_ALGORITHM")
JWT_ISSUER = _get_env("JWT_ISSUER")
JWT_ACCESS_TOKEN_LIFETIME_MINUTES = int(_get_env("JWT_ACCESS_TOKEN_LIFETIME_MINUTES"))
JWT_REFRESH_TOKEN_LIFETIME_DAYS = int(_get_env("JWT_REFRESH_TOKEN_LIFETIME_DAYS"))
CHAT_ADMIN_DELETE_RETENTION_DAYS = int(os.getenv("CHAT_ADMIN_DELETE_RETENTION_DAYS"))


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "EXCEPTION_HANDLER": "core.untils.exceptions.custom_exception_handler",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Finance AI API",
    "DESCRIPTION": "API docs for authentication and personal finance services.",
    "VERSION": "1.0.0",
    "SORT_OPERATION_PARAMETERS": False,
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SECURITY": [{"BearerAuth": []}],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}

# Email settings (read from .env)
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")


# CORS / Cookie settings
# Provide CORS_ALLOWED_ORIGINS as a comma-separated env var, e.g. http://localhost:3000,https://frontend.example.com
CORS_ALLOWED_ORIGINS = [
    h.strip() for h in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if h.strip()
]

# Allow credentials (HttpOnly cookies) to be sent and received
CORS_ALLOW_CREDENTIALS = True

# In DEBUG, if no origins provided, allow common localhost ports for frontend dev
if DEBUG and not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

# Optional: CSRF trusted origins (comma-separated env var)
CSRF_TRUSTED_ORIGINS = [
    h.strip() for h in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if h.strip()
]
